server:
  port: 8001
  address: :::
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/databases?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456@Root
