spring:
  datasource:
    url: jdbc:mysql://192.168.50.2:3306/databases?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: test
    password: 12345678@Test
    driver-class-name: com.mysql.jdbc.Driver
